mysql:
  host: localhost
  username: root
  password: ""
  database: szaman
  port: 3306
  ssl: false

inv:
  size: 36
  title: "&0Szaman"



max: "&cMAX"
no-level: "&cNie posiadasz odblokowanego!"

# czy ma byc walczone drop do eq
drop-to-inv: true

# type [ SQLITE, MYSQL ]
database: SQLITE

sqlite:
  name: "get_boxsettings"

# Type: [ ITEM, COINS ]
# Jeezeli ustawisz ITEM, pamietaj zeby ustawic
# walute /aszaman setodlamek
sell-type: ITEM

max-level: "&cMAX POZIOM"
price-info: "&cKoszt: &f{price} *"
extra-line-buy: "&eKliknij, aby zakupic!"

# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
music:
  victim: BLOCK_GRASS_BREAK
  player: BLOCK_ANVIL_PLACE

lang:
  success-upgrade: "&aPomyslnie ulepszono!"
  no-points: "&cNie posiadasz tylu punktow!"
  max-level: "&cPosiadasz najwyzszy poziom!"
  confinement-cooldown: "&cPosiadasz efekt uwiezienia!"
  vampirism-heal: "&aWampiryzm uleczył tobie &2{hp}♥"
  get-confinement: "&cZostałeś uwięziony przez &4{player} &cna &4{time}"
  put-in-confinement: "&cUwięziłeś gracza &4{player} &cna &4{time}"

drop-material:
  - "DIAMOND_ORE"
  - "DIAMOND_BLOCK"



data:
  health:
    1:
      cost: 5
      value: 2
    2:
      cost: 10
      value: 4
    3:
      cost: 20
      value: 6
    4:
      cost: 40
      value: 8
    5:
      cost: 50
      value: 10
  speed:
    1:
      cost: 5
      # 5% from default value
      value: 5
    2:
      cost: 10
      value: 10
    3:
      cost: 20
      value: 15
    4:
      cost: 40
      value: 20
    5:
      cost: 50
      value: 25
  strength:
    1:
      cost: 5
      value: 1
    2:
      cost: 10
      value: 2
    3:
      cost: 20
      value: 3
    4:
      cost: 40
      value: 4
    5:
      cost: 50
      value: 5
  vampirism:
    1:
      cost: 5
      value: 1.25
    2:
      cost: 10
      value: 2.5
    3:
      cost: 20
      value: 3.75
    4:
      cost: 40
      value: 5
    5:
      cost: 50
      value: 6.25
  boostdrop:
    1:
      cost: 5
      value: 1.5
    2:
      cost: 10
      value: 2
    3:
      cost: 20
      value: 2.5
    4:
      cost: 40
      value: 3
    5:
      cost: 50
      value: 3.5
  confinement:
    1:
      cost: 20
      # how long should the perk last
      # 1 level -> 2 second
      value: 2
    2:
      cost: 40
      value: 3
    3:
      cost: 60
      value: 4
    4:
      cost: 80
      value: 5
    5:
      cost: 100
      value: 6

background:
  '1':
    material: GRAY_STAINED_GLASS_PANE
    displayname: "&7"
    lore: []
    slots: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35]

# you need install my second plugin 'getFireworkNoLimit'
nolimit-firework:
  # price for 1pc of firework
  cost: 10
  command: "getfirework give {player} 1"
  enable: true
  slot: 15
  material: FIREWORK_ROCKET
  displayname: "&5Bez limitu fajerwerka"
  lore:
    - "&7"
    - "{price-info}"
    - "&7"
    - "&eKliknij, aby kupic!"



confinement:
  # chance to confinement user
  chance: 5.00
  enable: true
  slot: 11
  material: LEAD
  displayname: "&cPerk uwiezienia"
  format:
    active: "&a{level}. &7- &a{value}"
    no-active: "&c{level}. &7- &c{value}"
  lore:
    - "&7"
    - "&7Level: {level}"
    - "&7"
    - "&7Poziomy:"
    - "{info}"
    - "&7"
    - "{price-info}"
    - "&7"

health:
  enable: true
  slot: 20
  material: RED_DYE
  displayname: "&cPerk zycie"
  format:
    active: "&a{level}. &7- &a{value}"
    no-active: "&c{level}. &7- &c{value}"
  lore:
    - "&7"
    - "&7Level: {level}"
    - "&7"
    - "&7Poziomy:"
    - "{info}"
    - "&7"
    - "{price-info}"
    - "&7"
speed:
  enable: true
  slot: 21
  material: LIGHT_BLUE_DYE
  displayname: "&bPerk szybkosc"
  format:
    active: "&a{level}. &7- &a{value}"
    no-active: "&c{level}. &7- &c{value}"
  lore:
    - "&7"
    - "&7Level: {level}"
    - "&7"
    - "&7Poziomy:"
    - "{info}"
    - "&7"
    - "{price-info}"
    - "&7"

strength:
  enable: true
  slot: 22
  material: POTION
  displayname: "&cPerk sily"
  format:
    active: "&a{level}. &7- &a{value}"
    no-active: "&c{level}. &7- &c{value}"
  lore:
    - "&7"
    - "&7Level: {level}"
    - "&7"
    - "&7Poziomy:"
    - "{info}"
    - "&7"
    - "{price-info}"
    - "&7"

vampirism:
  enable: true
  slot: 23
  material: NETHERITE_SWORD
  displayname: "&cPerk wampiryzmu"
  format:
    active: "&a{level}. &7- &a{value}"
    no-active: "&c{level}. &7- &c{value}"
  lore:
    - "&7"
    - "&7Level: {level}"
    - "&7"
    - "&7Poziomy:"
    - "{info}"
    - "&7"
    - "{price-info}"
    - "&7"

boostdrop:
  enable: true
  slot: 24
  material: NETHERITE_PICKAXE
  displayname: "&cPerk dropu"
  format:
    active: "&a{level}. &7- &a{value}"
    no-active: "&c{level}. &7- &c{value}"
  lore:
    - "&7"
    - "&7Level: {level}"
    - "&7"
    - "&7Poziomy:"
    - "{info}"
    - "&7"
    - "{price-info}"
    - "&7"